### ISSUE TITLE
More baseline for these task

### ISSUE THREAD

**Issue by siaoliu** [younggyoseo/CQN#1]
Thank you to the authors for such an interesting work, which provides a guarantee for solving complex manipulation tasks in RL. 
Does the author would open more basic baseline such as DrQv2+ in  the soon?

**Comment by younggyoseo** [comment]
Hi, thank you for your interest in our work. And that's a good point, we will add DrQ-v2+ soon as it's not that difficult to add

**Comment by younggyoseo** [comment]
Added a support for DrQ-v2+, Please check the latest commit and README. Thank you!
