### ISSUE TITLE
Some issues about the strong BC baseline ACT

### ISSUE THREAD

**Issue by siaoliu** [younggyoseo/CQN#2]
Thanks a lot to the author for this wonderful work.
In order to better understand its contribution, I try to train the ACT model with original codebase and collected data. However, I notice that there is a severe performance degradation. 
Could the author provide some changed hyper-parameters adapted to RLBench data or open source the re-implementation version?
Thank you very much, looking forward to your reply.

**Comment by younggyoseo** [comment]
Hi, I'd like to recommend you to check ACT implementation and training scripts at https://github.com/robobase-org/robobase.
